// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XtremeIdiots.Portal.DataLib
{
    public partial class ChatMessage
    {
        [Key]
        public Guid Id { get; set; }
        [Required]
        [StringLength(50)]
        public string GameServerId { get; set; }
        public Guid PlayerId { get; set; }
        [Required]
        [StringLength(50)]
        public string Username { get; set; }
        [Required]
        public string Message { get; set; }
        [Required]
        [StringLength(50)]
        public string Type { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Timestamp { get; set; }

        [ForeignKey(nameof(GameServerId))]
        [InverseProperty("ChatMessages")]
        public virtual GameServer GameServer { get; set; }
        [ForeignKey(nameof(PlayerId))]
        [InverseProperty("ChatMessages")]
        public virtual Player Player { get; set; }
    }
}