trigger:
  branches:
    include:
    - 'main'

pr: none

variables:
  terraformWorkingDirectory: '$(Build.sourcesDirectory)/tf-deploy'
  backendServiceArm: 'arm-portal-core-dev'
  backendAzureRmResourceGroupName: 'rg-portal_tfstate-dev-eastus-01'
  backendAzureRmStorageAccountName: 'saportaltfdeveastus01'
  backendAzureRmContainerName: 'tfstate'
  backendAzureRmKey: 'portal-core-dev.tfstate'
  environmentServiceNameAzureRM: 'arm-portal-core-dev'
  varFile: './../tf-vars/dev.tfvars'

resources:
  repositories:
    - repository: ado-pipeline-templates
      type: github
      name: XtremeIdiots/ado-pipeline-templates
      endpoint: XtremeIdiots

stages:
- stage: Build

  jobs:
  - template: jobs/build-function-app.yml@ado-pipeline-templates
    parameters:
      publishArtifact: true

  - template: jobs/build-sql-database.yml@ado-pipeline-templates
    parameters:
      publishArtifact: true

- stage: Deploy

  jobs:
  - template: jobs/terraform-validate-and-plan.yml@ado-pipeline-templates
    parameters:
      jobName: TerraformValidateAndPlan
      workingDirectory: '$(terraformWorkingDirectory)'
      backendServiceArm: '$(backendServiceArm)'
      backendAzureRmResourceGroupName: '$(backendAzureRmResourceGroupName)'
      backendAzureRmStorageAccountName: '$(backendAzureRmStorageAccountName)'
      backendAzureRmContainerName: '$(backendAzureRmContainerName)'
      backendAzureRmKey: '$(backendAzureRmKey)'
      environmentServiceNameAzureRM: '$(environmentServiceNameAzureRM)'
      varFile: '$(varFile)'

  - job: ReviewAndApproveTerraform
    dependsOn: TerraformValidateAndPlan
    pool: server
    timeoutInMinutes: 60
    steps:   
    - task: ManualValidation@0
      inputs:
          instructions: 'Validate the terraform plan from previous stage and either resume/reject.'

  - template: jobs/terraform-plan-and-apply.yml@ado-pipeline-templates
    parameters:
      jobName: TerraformPlanAndApply
      dependsOn: ReviewAndApproveTerraform
      workingDirectory: '$(terraformWorkingDirectory)'
      backendServiceArm: '$(backendServiceArm)'
      backendAzureRmResourceGroupName: '$(backendAzureRmResourceGroupName)'
      backendAzureRmStorageAccountName: '$(backendAzureRmStorageAccountName)'
      backendAzureRmContainerName: '$(backendAzureRmContainerName)'
      backendAzureRmKey: '$(backendAzureRmKey)'
      environmentServiceNameAzureRM: '$(environmentServiceNameAzureRM)'
      varFile: '$(varFile)'

  - template: jobs/deploy-function-app.yml@ado-pipeline-templates
    parameters:
      jobName: DeployFunctionApp
      dependsOn: TerraformPlanAndApply
      environmentServiceNameAzureRM: '$(environmentServiceNameAzureRM)'

  - job: DeploySqlDatabase
    dependsOn: TerraformPlanAndApply

    pool: windows-latest

    variables:
    - name: sql_server_name
      value: $[ dependencies.TerraformPlanAndApply.outputs['terraform_output.sql_server_name'] ]
    - name: sql_database_name
      value: $[ dependencies.TerraformPlanAndApply.outputs['terraform_output.sql_database_name'] ]
    - name: sql_admin_username
      value: $[ dependencies.TerraformPlanAndApply.outputs['terraform_output.sql_admin_username'] ]
    - name: sql_admin_password
      value: $[ dependencies.TerraformPlanAndApply.outputs['terraform_output.sql_admin_password'] ]

    steps: 
      - download: current
        displayName: 'Download database artifact'
        artifact: database

      - task: SqlAzureDacpacDeployment@1
        inputs:
          azureSubscription: '$(environmentServiceNameAzureRM)'
          ServerName: '$(sql_server_name)'
          DatabaseName: '$(sql_database_name)'
          SqlUsername: '$(sql_admin_username)'
          SqlPassword: '$(sql_admin_password)'
          DacpacFile: '$(Pipeline.Workspace)/database/database.dacpac'
          