trigger:
  branches:
    include:
    - 'sandbox/*'

pr: none

variables:
  terraformWorkingDirectory: '$(Build.sourcesDirectory)/tf-deploy'
  backendServiceArm: 'arm-portal-core-sandbox'
  backendAzureRmResourceGroupName: 'rg-portal_tfstate-box-eastus-01'
  backendAzureRmStorageAccountName: 'saportaltfboxeastus01'
  backendAzureRmContainerName: 'tfstate'
  backendAzureRmKey: 'portal-core-box.tfstate'
  environmentServiceNameAzureRM: 'arm-portal-core-sandbox'
  varFile: './../tf-vars/sandbox.tfvars'

pool: Dedicated

resources:
  repositories:
    - repository: ado-pipeline-templates
      type: github
      name: XtremeIdiots/ado-pipeline-templates
      endpoint: XtremeIdiots

stages:
- stage: Build

  jobs:
  - template: jobs/build-function-app.yml@ado-pipeline-templates
    parameters: 
      jobName: 'BuildEventsFunctionApp'
      projectName: 'events-func'
      publishArtifact: true

  - template: jobs/build-function-app.yml@ado-pipeline-templates
    parameters: 
      jobName: 'BuildIngestFunctionApp'
      projectName: 'ingest-func'
      publishArtifact: true

  - template: jobs/build-function-app.yml@ado-pipeline-templates
    parameters: 
      jobName: 'BuildRepositoryFunctionApp'
      projectName: 'repository-func'
      publishArtifact: true

  - template: jobs/build-function-app.yml@ado-pipeline-templates
    parameters: 
      jobName: 'BuildBanSyncFunctionApp'
      projectName: 'bansync-func'
      publishArtifact: true

  - template: jobs/build-web-app.yml@ado-pipeline-templates
    parameters: 
      jobName: 'BuildMgmtWebApp'
      projectName: 'mgmt-web'
      publishArtifact: true

  - template: jobs/build-web-app.yml@ado-pipeline-templates
    parameters: 
      jobName: 'BuildAdminWebApp'
      projectName: 'admin-web'
      publishArtifact: true

  - template: jobs/build-web-app.yml@ado-pipeline-templates
    parameters: 
      jobName: 'BuildPublicWebApp'
      projectName: 'public-web'
      publishArtifact: true

  - template: jobs/build-web-app.yml@ado-pipeline-templates
    parameters: 
      jobName: 'BuildRepositoryWebApi'
      projectName: 'repository-webapi'
      publishArtifact: true

  - template: jobs/build-sql-database.yml@ado-pipeline-templates
    parameters:
      publishArtifact: true

- stage: Deploy

  variables:
  - group: b2c-tenant

  jobs:
  - template: jobs/terraform-plan-and-apply.yml@ado-pipeline-templates
    parameters:
      jobName: TerraformPlanAndApply
      workingDirectory: '$(terraformWorkingDirectory)'
      backendServiceArm: '$(backendServiceArm)'
      backendAzureRmResourceGroupName: '$(backendAzureRmResourceGroupName)'
      backendAzureRmStorageAccountName: '$(backendAzureRmStorageAccountName)'
      backendAzureRmContainerName: '$(backendAzureRmContainerName)'
      backendAzureRmKey: '$(backendAzureRmKey)'
      environmentServiceNameAzureRM: '$(environmentServiceNameAzureRM)'
      varFile: '$(varFile)'
      additionalCommandOptions: '-var="b2c_tenant_client_id=$(client-id)" -var="b2c_tenant_client_secret=$(client-secret)"'

  - template: jobs/deploy-function-app.yml@ado-pipeline-templates
    parameters:
      projectName: events-func
      jobName: DeployEventsFunctionApp
      dependsOn: TerraformPlanAndApply
      environmentServiceNameAzureRM: '$(environmentServiceNameAzureRM)'

  - template: jobs/deploy-function-app.yml@ado-pipeline-templates
    parameters:
      projectName: ingest-func
      jobName: DeployIngestFunctionApp
      dependsOn: TerraformPlanAndApply
      environmentServiceNameAzureRM: '$(environmentServiceNameAzureRM)'

  - template: jobs/deploy-function-app.yml@ado-pipeline-templates
    parameters:
      projectName: repository-func
      jobName: DeployRepositoryFunctionApp
      dependsOn: TerraformPlanAndApply
      environmentServiceNameAzureRM: '$(environmentServiceNameAzureRM)'

  - template: jobs/deploy-function-app.yml@ado-pipeline-templates
    parameters:
      projectName: bansync-func
      jobName: DeployBanSyncFunctionApp
      dependsOn: TerraformPlanAndApply
      environmentServiceNameAzureRM: '$(environmentServiceNameAzureRM)'

  - template: jobs/deploy-web-app.yml@ado-pipeline-templates
    parameters: 
      projectName: 'mgmt-web'
      jobName: 'DeployMgmtWebApp'
      dependsOn: TerraformPlanAndApply
      environmentServiceNameAzureRM: '$(environmentServiceNameAzureRM)'

  - template: jobs/deploy-web-app.yml@ado-pipeline-templates
    parameters: 
      projectName: 'admin-web'
      jobName: 'DeployAdminWebApp'
      dependsOn: TerraformPlanAndApply
      environmentServiceNameAzureRM: '$(environmentServiceNameAzureRM)'

  - template: jobs/deploy-web-app.yml@ado-pipeline-templates
    parameters: 
      projectName: 'public-web'
      jobName: 'DeployPublicWebApp'
      dependsOn: TerraformPlanAndApply
      environmentServiceNameAzureRM: '$(environmentServiceNameAzureRM)'

  - template: jobs/deploy-web-app.yml@ado-pipeline-templates
    parameters: 
      projectName: 'repository-webapi'
      jobName: 'DeployRepositoryWebApi'
      dependsOn: TerraformPlanAndApply
      environmentServiceNameAzureRM: '$(environmentServiceNameAzureRM)'

  - template: jobs/deploy-sql-database.yml@ado-pipeline-templates
    parameters:
      jobName: DeploySqlDatabase
      dependsOn: TerraformPlanAndApply
      environmentServiceNameAzureRM: '$(environmentServiceNameAzureRM)'
      sqlCmdArgs: '"/Variables:env=box" "/Variables:region=eastus" "/Variables:instance=01"'
