trigger:
  branches: 
    include:
    - '*'

variables:
  terraformWorkingDirectory: '$(Build.sourcesDirectory)/tf-deploy'
  backendServiceArm: 'arm-portal-core-dev'
  backendAzureRmResourceGroupName: 'rg-portal_tfstate-dev-eastus-01'
  backendAzureRmStorageAccountName: 'saportaltfdeveastus01'
  backendAzureRmContainerName: 'tfstate'
  backendAzureRmKey: 'portal-core-dev.tfstate'
  environmentServiceNameAzureRM: 'arm-portal-core-dev'
  varFile: './../tf-vars/dev.tfvars'
  buildConfiguration: 'Release'


resources:
  repositories:
    - repository: ado-pipeline-templates
      type: github
      name: XtremeIdiots/ado-pipeline-templates
      endpoint: XtremeIdiots

stages:
- stage: Validate

  jobs:
  - template: jobs/terraform-validate-and-plan.yml@ado-pipeline-templates
    parameters:
      workingDirectory: '$(terraformWorkingDirectory)'
      backendServiceArm: '$(backendServiceArm)'
      backendAzureRmResourceGroupName: '$(backendAzureRmResourceGroupName)'
      backendAzureRmStorageAccountName: '$(backendAzureRmStorageAccountName)'
      backendAzureRmContainerName: '$(backendAzureRmContainerName)'
      backendAzureRmKey: '$(backendAzureRmKey)'
      environmentServiceNameAzureRM: '$(environmentServiceNameAzureRM)'
      varFile: '$(varFile)'

  - job: build
      steps:
      - task: UseDotNet@2
        inputs:
          version: 6.0.x
          performMultiLevelLookup: true
          includePreviewVersions: true
      
      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'
          projects: '**/*.csproj'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: '**/*.csproj'
          arguments: '--configuration $(buildConfiguration)'
        displayName: 'dotnet build $(buildConfiguration)'